version: '3.8'

# Descomente a seção abaixo caso queira rodar o backend e banco também
# include:
#   - path: ../Escola-Conectada-API/docker-compose.dev.yml
#     required: false

services:
  # Frontend Angular
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: escola-conectada-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    networks:
      - escola-conectada-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4200/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

# Networks
networks:
  escola-conectada-network:
    driver: bridge
    name: escola-conectada-network
