version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile.dev
    container_name: escola-conectada-frontend
    restart: unless-stopped
    command: >
      ng serve --host 0.0.0.0 --port 4200 --poll 1000 --proxy-config proxy.conf.json
    ports:
      - "4200:4200"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    networks:
      - escola-conectada-network

networks:
  escola-conectada-network:
    external: true
    name: escola-conectada-network